name: Lint and Test

on: pull_request
permissions:
  contents: write
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Packages
        run: |
          npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: CI Badges
        uses: GaelGirodon/ci-badges-action@v1.1.0
        with:
          gist-id: f9b687636482339cabd6a8c4b369f3eb
          token: ${{ secrets.GIST_TOKEN }}
